source/config/routes.rb
Digesto::Application.routes.draw do

  resources :categories

  get "backups/index"

  get "backups/new"

  get "backups/destroy"

  get "backups/show"

  get "/zm" => redirect("/regulations")

  resources :words
  resources :expressions
  resources :regulation_types
  resources :types 
  resources :issuers
  resources :institutions
  resources :backups

  resources :regulations do
    post 'mass_create', :action => :mass_create, :on => :collection, :as => :mass_create
    get 'missing', :action => :missing, :on => :collection, :as => :missing
    member do
      get 'view(/:version)', :action => :file, :disposition => "inline", :as => :view
      get 'download(/:version)', :action => :file, :disposition => "attachment", :as => :download
    end
  end

  devise_for :users
  resources :users

  get 'config' => 'sysconfigs#edit', :as => :edit_config
  post 'config' => 'sysconfigs#update', :as => :update_config
  put 'config' => 'sysconfigs#update', :as => :update_config

  match 'view/tmp/*tmp_file' => 'file#file', :as => :view_temp
  match 'view/:disposition/:class_name/:field_name/:id(/:version)'  => 'file#file', :as => :view

  root :to => "regulations#index"

end

source/app/models/regulation.rb
# encoding: UTF-8

class Regulation < ActiveRecord::Base

  scope :confirmed, where(:confirmation => true)

  has_many :indices, :dependent => :destroy
  has_many :words, :through => :indices

  has_many :regulation_category, :dependent => :destroy
  has_many :categories, :through => :regulation_category

  belongs_to :regulation_type
  has_one :type, :through => :regulation_type
  has_one :issuer, :through => :regulation_type
  #validates_presence_of :number, :date, :regulation_type, :description
  validates_presence_of :number, :date, :regulation_type
  validates_numericality_of :number
  validates_acceptance_of :confirmation, :accept => true

  has_many :attachments
  accepts_nested_attributes_for :attachments, :allow_destroy => true
  accepts_nested_attributes_for :categories, :allow_destroy => true

  MONTHS={ 
    :ene => 1,
    :feb => 2,
    :mar => 3,
    :abr => 4,
    :may => 5,
    :jun => 6,
    :jul => 7,
    :ago => 8,
    :sep => 9,
    :set => 9,
    :oct => 10,
    :nov => 11,
    :dic => 12,
  }


  attr_protected :text_content

  mount_uploader :file, PdfUploader

  def self.years_range
    #start=Regulation.order(:date).where("date IS NOT NULL").first.date rescue Date.today
    #finnish=Regulation.order(:date).where("date IS NOT NULL").last.date rescue Date.today
    #(start.year..finnish.year).to_a
    Regulation.select(:date).all.map{|r| r.date.year rescue nil}.compact.uniq.sort
  end

  def title
    [issuer.abbreviation, date.year, type.abbreviation, ("000"+number.to_s)[-3..-1]].join "-"  rescue id.to_s
  end

  def full_title
    [type.name, issuer.name,"-","Nro.",("000"+number.to_s)[-3..-1],"-","Año",date.year].join " "  rescue id.to_s
  end

  def description_to_show
    description.blank? ? full_title : description 
  end

  before_validation :infer_missing_data
  before_save :update_index_if_needed

  def text_content
    @text_content ||= extract_data_from_pdf || ""
  end

  def outdated?
    (not confirmation) and (Expression.order(:updated_at).last.updated_at > updated_at)
  end

  def infer_missing_data(*params)
    options=params.extract_options!
    force=options[:force]
    infer_abstract if abstract.blank? or force
    infer_date if date.nil? or force
    infer_regulation_type if regulation_type_id.nil? or force
    infer_regulation_number if number.nil? or force
    unless self.confirmation
      infer_description if description.blank? or force
    end
  end

  def update_index_if_needed
    has_categories=(categories.count != 0 ? true : false)
    if self.changed.include?("abstract") or self.changed.include?("description") or self.words.count == 0
      self.update_index
    end
  end
  def update_index
      text=(self.abstract.to_s+" "+self.description.to_s).mb_downcase.to_ascii
      #text.gsub!(/[^\w \n]*/,"")
      indexable = []
      indexable += text.scan(/\w+/)
      indexable += text.scan(/[0-9\.]+/)
      self.words=indexable.uniq.map{|w| Word.where(:word => w).first || Word.new(:word => w)}
  end

  private

  def extract_data_from_pdf
    if file?
      text = ""
      File.open(self.file.url(:text), 'r') do |f|
        text = f.read
      end rescue ""
      text ||= "" 
      # text = `pdftotext -layout #{file.path} -` || ""

      # text.encode!('utf-8')

      text.gsub!("\f","\n\n") # Salto de pagina a salto de parrafo
      text.gsub!(/\ +/," ") # Elimina espacios dobles
      text.gsub!(/\ *\n\ */,"\n") # Elimina espacios al final y principio de linea

      Expression.type(:paragraph_starter).all.each do |s|
          text.gsub!(/\ *(#{s.computed_regex})/,"\n\n"+'\1')
      end
      Expression.type(:paragraph_finisher).all.each do |f|
          text.gsub!(/(#{f.computed_regex})\ */,'\1'+"\n\n")
      end

      text.gsub!(/-\n/,"") # Elimina separacion en silabas
      text.gsub!(/\n{2,}/,"\302\205").gsub!("\n"," ") rescue nil # convierte los dobles (o mas) saltos de linea en salto de parrafo

      text.gsub!(/(\302\205)+/,"\n\n") # convierte los saltos de parrafo a doble salto de linea

      Expression.type(:cleaner).all.each do |cs|
        text.gsub!(/#{cs.computed_regex}/,"")
      end

      text.gsub!(/\n\s*\n/,"\n\n") # Si despues de la eliminacion quedan tres o mas saltos (o saltos con espacios) los dejo en dos

      text.strip
    end
  end rescue nil

  def infer_abstract
    self.abstract=text_content 
    self.confirmation=false unless self.abstract.blank?
  end

  def infer_description
    desc=nil
    Expression.type(:description_detector).all.each do |dd|
      desc ||= self.abstract.scan(/#{dd.computed_regex}/).flatten.first.to_s unless self.abstract.nil?
    end
    self.description=desc
    #self.confirmation=false unless desc.nil?
  end

  def infer_date
    idate=nil
    Expression.type(:date_detector).all.each do |dd|
      idate ||= text_content.scan(/#{dd.computed_regex}/).first rescue nil
    end
    if idate 
      day=idate[0].to_i
      month=MONTHS[idate[1][0..2].mb_downcase.to_sym].to_i
      year=idate[2].to_i
      cdate=Date.civil(year,month,day) rescue nil
      self.date=cdate unless cdate.nil?
    end rescue nil
    self.confirmation=false unless self.date.nil?
  end

  def infer_regulation_type
    RegulationType.joins(:expressions).includes(:expressions).each do |rt|
      rt.expressions.each do |e|
        self.regulation_type_id=rt.id if text_content[/#{e.computed_regex}/]
      end
    end
    self.confirmation=false unless self.regulation_type_id.nil?
  end

  def infer_regulation_number
    Type.joins(:expressions).each do |t|
      t.expressions.each do |e|
        detected=text_content[/#{e.computed_regex}\s*\d+/][/\d+/].to_i rescue nil
          if detected
            self.number=detected
          end
      end
    end
    self.confirmation=false unless self.number.blank?
  end

end

source/app/models/regulation_type.rb
class RegulationType < ActiveRecord::Base
  default_scope joins(:issuer).joins(:type).order("issuers.name","types.name")
  belongs_to :issuer
  belongs_to :type
  has_many :regulations, :dependent => :restrict

  has_many :expressions, :as => :regexable
  accepts_nested_attributes_for :expressions, :allow_destroy => true

  def display_name
    [self.type.name,self.issuer.name,self.issuer.institution.name].join " "
  end
end

source/app/controllers/regulations_controller.rb
class RegulationsController < ApplicationController
  load_and_authorize_resource

  def index
    @regulations=Regulation.includes(:issuer).includes(:type).includes(:attachments).includes(:categories)
    if can? :edit, Regulation
      @regulations=@regulations
    else
      @regulations=@regulations.confirmed
    end
    @regulations=@regulations.where("date >= ? and date <= ?","#{params[:search_year]}0101","#{params[:search_year]}1231") unless params[:search_year].blank?  
    @regulations=@regulations.where(:types => { :id => params[:search_type]}) unless params[:search_type].blank?

    unless params[:search_category].blank?
      if params[:search_category] == "-" then
        @regulations=@regulations.where(:has_categories => false)
      else
        @regulations=@regulations.where(:categories => { :id => params[:search_category]})
      end
    end

    @regulations=@regulations.where(:issuers => { :id => params[:search_issuer]}) unless params[:search_issuer].blank?
    @regulations=@regulations.where(:number => params[:search_number]) unless params[:search_number].blank?
		@regulations=@regulations.order("confirmation").order(params[:order] != "updated_at" ? "regulations.date DESC" : "regulations.updated_at DESC").order("number DESC")
    @regulations_for_feed=@regulations.limit(50)

    search=params[:search]
    unless search.blank?
      search.gsub!("\"","")
      searchable = []
      searchable += search.mb_downcase.to_ascii.scan(/\w+/)
      searchable += search.mb_downcase.to_ascii.scan(/[0-9\.]+/)

      ids_ary=searchable.map{ |word_word| (Word.where(:word => word_word).joins(:indices).first || Word.new).regulation_ids}
      regulation_ids=ids_ary.shift
      ids_ary.each{|ids| regulation_ids &= ids}
      @regulations=@regulations.where(:id => regulation_ids)
    end

    @regulations_count=@regulations.size
		@regulations=@regulations.paginate(:per_page => 7, :page => params[:page])
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    if @regulation.save
      redirect_back_or_to regulations_path
    else
      render :action => "new"
    end
  end

  def mass_create
    ajax_upload = params[:qqfile].is_a?(String)
    filename = ajax_upload  ? params[:qqfile] : params[:qqfile].original_filename
    extension = filename.split('.').last
    # Creating a temp file
    tmp_file=""
    while tmp_file.blank? || File.exists?(tmp_file) do
      tmp_file = "#{Rails.root}/tmp/uploaded.#{Time.now.to_f.to_s}.#{extension}"
    end
    # Save to temp file
    File.open(tmp_file, 'wb') do |f|
      if ajax_upload
        f.write  request.body.read
      else
        f.write params[:qqfile].read
      end
    end
    @regulation=Regulation.new
    @regulation.file = File.open(tmp_file)
    @regulation.infer_missing_data
    @result=@regulation.save(:validate => false) ? { :success => true } : "error"
    respond_to do |format|
       format.js { render :json => @result.to_json }
    end
  end

  def update
    @regulation=Regulation.find params[:id], :readonly => false
    if @regulation.update_attributes(params[:regulation])
      redirect_back_or_to regulations_path
    else
      render :action => "edit" 
    end
  end

  def destroy
    @regulation.destroy
    redirect_to regulations_path
  end

  def missing
    @missing={}
    regulations=Regulation.joins(:issuer,:type).order(:date)
    regulations=regulations.group_by{|r| "#{r.type.abbreviation}-#{r.issuer.abbreviation}/#{r.date.year}" rescue nil}

    regulations.each do |k,v|
      v=v.map{|r| r.number rescue nil}.compact.sort.uniq
      last=v.last
      missing=(1..last).map{|n| n unless v.include? n}.compact

      intervals=[[missing.first,missing.first]]

      missing.each do |m|
        if intervals.last.last+1 >= m
          intervals.last[1]=m
        else
          intervals << [m,m]
        end
      end

      @missing[k]=intervals.map{|i| i.first == i.last ? i.first.to_s : i.first.to_s+"-"+i.last.to_s} unless k.blank?

    end
  end

end

source/app/helpers/regulations_helper.rb
module RegulationsHelper
end

source/app/views/regulations/_form.html.erb
<%= semantic_form_for(@regulation, :html => {:multipart => true}) do |f| %>
  <%= f.inputs :class => "half" do %>
    <% label=image_tag( file_url(@regulation, :file, :icon) , :align => "top")+" "+s_t(Regulation,:file) if @regulation.file? %>
    <%= f.input :file, :as => :file, :label => label %>
    <%= f.hidden_field :file_cache %>

    <% if @regulation.file? %>
      <%= f.input :regulation_type, :group_by => :type,:input_html => { :class => "autocomplete", "data-placeholder" => s_t(Type, :select, :action)}, :allow_blank => true %>
      <%= f.input :number, :input_html => { :size => 5 } %>
      <%= f.input :date, :start_year => 1980 %>
      <%= f.input :description, :input_html => { :class => "elastic", :rows => 2 } %>
      <%= render :partial => "attachments/attachments", :locals => { :f =>  f, :legend => s_t(Attachment,:collection) }  %>
      <%= f.input :categories, :as => :check_boxes %>
      <%= f.input :confirmation %>
    <% end %>
  <% end %>
  <%= image_tag( file_url(@regulation, :file, :cover), :class => "half" ) if @regulation.file? %>
  <div class="floatKiller"></div>
  <%= f.buttons %>

  <% if @regulation.file? %>
    <%= f.inputs do %>
      <%= f.input :abstract, :input_html => { :class => "elastic", :rows => 2 } %>
    <% end %>
    <%= f.buttons %>
  <% end %>
<% end %>

source/app/views/regulations/_mass_uploader.erb
<% if can? :mass_create, Regulation %> 
<div id="regulation-uploader">    
</div>
<script>        
  function createUploader(){            
    var uploader = new qq.FileUploader({
      element: document.getElementById('regulation-uploader'),
      action: <%= mass_create_regulations_path.to_json.html_safe %>,
      debug: false,
      csrf: true,
      maxConnections: 1
    });           
  }
  window.onload = createUploader;     
</script> 
<% end %>

source/app/views/regulations/_regulation.erb
<tr class="<%= "unconfirmed" unless regulation.confirmation? %>">
  <td class="nowrap">
    <%= regulation.title %><br/>
    <%= I18n.l regulation.date rescue nil %> 
    <br/>
    (<%= s_t Regulation, :updated_at %>: <%= I18n.l regulation.updated_at.to_date rescue nil %>)<br/>
  </td>
  <td>
    <div class="text description"> <%= link_to regulation.description_to_show, regulation_path(regulation) %> </div>
    <div class="text abstract" style="display:none"> <%= regulation.abstract %> </div>
  </td>
  <td>
    <%= regulation.categories.map{|cat| cat.name}.to_sentence  %>
  </td>
  <td class="nowrap"> <%= rud_links(regulation) %><br/>
    <%= regulation.attachments.size+1 %> <%= image_tag "/images/crud/attachment.16.png", :align => "top" %> 
  </td>
  </td>
</tr>

source/app/views/regulations/edit.html.erb
<h1><%= s_t Regulation, :edit, :actions %></h1>
<%= render 'form' %>

source/app/views/regulations/index.html.erb
<h1><%= s_t Regulation, :index, :actions %></h1>
<table class="index">
  <tr>
    <th colspan="999">
      <div class="search">
        <%= form_tag nil, :method => "get", :remote => false do %>
          <ol>
            <li>
            <label>
              <%=s_t(Category, :collection) %>
              <%= select_tag :search_category, options_for_select([nil]+[["Sin categorías","-"]]+Category.all.map{|i| [i.name,i.id]}, params[:search_category]), :class => "autocomplete", "data-placeholder" => s_t(Category, :select, :actions), :style => "min-width:180px" %>
            </label>
            </li>
            <li> <label><%=s_t(Word, :collection) %></label><%= text_field_tag  :search, params[:search], :class => "search", :size => 50 %></li>
            <li> <%= submit_tag s_t(Regulation, :search, :action), :id => "commit" %></li>
          </ol>
          <ol class="order">
            <li>
            <label><%=s_t(Regulation, :order_by) %></label>
            <%= radio_button_tag :order, :updated_at, (params[:order] == "updated_at") %><%= s_t(Regulation, :updated_at) %>
            <%= radio_button_tag :order, :date, (params[:order] != "updated_at") %><%= s_t(Regulation, :date) %>
            </li>
          </ol>
          <ol class="advanced">
            <li>
            <label><%=s_t(Regulation, :type)%></label>
            <%= select_tag  :search_type, options_for_select([nil]+Type.all.map{|i| [i.name,i.id]}, params[:search_type]), :class => "autocomplete", "data-placeholder" => s_t(Type, :select, :actions), :style => "min-width:160px" %>
            </li>

            <li><label><%=s_t(Regulation, :issuer)%></label><%= select_tag  :search_issuer, options_for_select([nil]+Issuer.all.map{|i| [i.display_name,i.id]}, params[:search_issuer]), :class => "autocomplete", "data-placeholder" => s_t(Issuer, :select, :actions), :style => "min-width:160px" %></li>
            <li><label><%=s_t(Regulation, :number)%></label><%= text_field_tag  :search_number, params[:search_number], :class => "numeric", :size => 3 %></li>
            <li><label><%=s_t(Regulation, :year)%></label>
            <%= select_tag  :search_year, options_for_select([nil]+Regulation.years_range.reverse.map{|i| [i,i]}, params[:search_year]), :class => "autocomplete", :style => "min-width:100px", "data-placeholder" => s_t(Regulation, :year) %>
            </li>
          </ol>
        <%end %>
      </div>
      <% if can? :create, Regulation %><label> <%= link_to s_t(Regulation, :missing), :missing_regulations %></label><% end %>
    </th>
  </tr>
  <th colspan="999">
    <div style="float: left;"> <%= "#{@regulations_count} #{s_t(Regulation, :collection)}" %> </div>
    <%= will_paginate @regulations, :previous_label => s_t(Regulation,:previous), :next_label => s_t(Regulation,:next), :inner_window => 2, :outer_window => 1, :separaton => "..."  %></th>
  <% @regulations.each do |regulation| %>
    <%= render :partial => "regulation", :object => regulation %>
  <% end %>
  <tr>
  </tr>
  <tr>
    <th colspan="999" class="pagination">
      <%= create_link(Regulation) %> 
      <%= render :partial => "mass_uploader" if can? :create, Regulation %>
    </th>
  </tr>
</table>

source/app/views/regulations/missing.erb
<h1><%= s_t Regulation, :missing %> </h1>
<p><%= s_t Regulation, :missing, :hints %></p>
<% @missing.each do |k,v| %>
  <h2> <%= k %></h2>
  <%= v.to_sentence %>
<% end %>

source/app/views/regulations/new.html.erb
<h1><%= s_t Regulation, :new, :action %></h1>
<%= render 'form' %>

source/app/views/regulations/show.erb
<h2>
  <%= rud_links @regulation %>
  <%= @regulation.title %> - <%= I18n.l @regulation.date rescue nil %>
</h2>
<div>
  <div class="text"> <%= @regulation.description_to_show %> </div>
</div>
<div class="floatKiller"></div>
  <div class="attachments">
    <h2>
      <%= image_tag("crud/attachment.16.png", :size => "16x16") %> <%= s_t(Regulation, :files) %>
    </h2>
  <div class="attachment main">
        <div>
          <%= link_to image_tag( file_url(@regulation, :file, :thumb), :size => "90x120"), file_url(@regulation,:file), :target => "_blank" rescue nil %>
        </div>
          <%= link_to("<span>#{s_t(@regulation,:download,:action)}</span>".html_safe, file_url(@regulation, :file, nil, :attachment), :class => "download" )  %>
          <%= @regulation.type.try(:name) %>
      </div>
    <% @regulation.attachments.each do |a| %>
      <div class="attachment">
        <div>
        <%= link_to image_tag( file_url(a, :file, :thumb), :size => "90x120"), file_url(a,:file), :target => "_blank" %>
        </div>
          <%= link_to("<span>#{s_t(a,:download,:action)}</span>".html_safe, file_url(a, :file, nil, :attachment), :class => "download" )  %>
          <%= a.name %>
      </div>
    <% end %>
  </div>
  <div class="floatKiller"></div>