source/config/routes.rb
Digesto::Application.routes.draw do

  resources :categories

  get "backups/index"

  get "backups/new"

  get "backups/destroy"

  get "backups/show"

  get "/zm" => redirect("/regulations")

  resources :words
  resources :expressions
  resources :regulation_types
  resources :types 
  resources :issuers
  resources :institutions
  resources :backups

  resources :regulations do
    post 'mass_create', :action => :mass_create, :on => :collection, :as => :mass_create
    get 'missing', :action => :missing, :on => :collection, :as => :missing
    member do
      get 'view(/:version)', :action => :file, :disposition => "inline", :as => :view
      get 'download(/:version)', :action => :file, :disposition => "attachment", :as => :download
    end
  end

  devise_for :users
  resources :users

  get 'config' => 'sysconfigs#edit', :as => :edit_config
  post 'config' => 'sysconfigs#update', :as => :update_config
  put 'config' => 'sysconfigs#update', :as => :update_config

  match 'view/tmp/*tmp_file' => 'file#file', :as => :view_temp
  match 'view/:disposition/:class_name/:field_name/:id(/:version)'  => 'file#file', :as => :view

  root :to => "regulations#index"

end

source/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :regulation_category, :dependent => :destroy
  has_many :regulations, :through => :regulation_category
end

source/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(params[:category])

    if @category.save
      redirect_to(@category, :notice => 'Category was successfully created.') 
    else
      render :action => "new" 
    end
  end

  def update
    @category = Category.find(params[:id])

    if @category.update_attributes(params[:category])
      redirect_to(@category, :notice => 'Category was successfully updated.') 
    else
      render :action => "edit" 
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to(categories_url) 
  end
end

source/app/helpers/categories_helper.rb
module CategoriesHelper
end

source/app/views/categories/_form.html.erb
<%= semantic_form_for(@category) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

source/app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

source/app/views/categories/index.html.erb
<h1><%= s_t Category, :index, :actions %></h1>
<table class="index">
  <tr>
    <th><%= s_t(Category, :name) %></th>
    <th><%= s_t(Category, :description) %></th>
    <th> </th>
  </tr>
  <% @categories.each do |category| %>
    <tr>
      <td class="nowrap"><%= category.name %></td>
      <td><%= category.description %></td>
      <td class="nowrap"><%= rud_links(category) %></td>
    </tr>
  <% end %>
  <tr>
    <th colspan="999"> <%= create_link(Category) %> </th>
  </tr>
</table>

source/app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

source/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Description:</b>
  <%= @category.description %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>