source/config/routes.rb
Digesto::Application.routes.draw do

  resources :categories

  get "backups/index"

  get "backups/new"

  get "backups/destroy"

  get "backups/show"

  get "/zm" => redirect("/regulations")

  resources :words
  resources :expressions
  resources :regulation_types
  resources :types 
  resources :issuers
  resources :institutions
  resources :backups

  resources :regulations do
    post 'mass_create', :action => :mass_create, :on => :collection, :as => :mass_create
    get 'missing', :action => :missing, :on => :collection, :as => :missing
    member do
      get 'view(/:version)', :action => :file, :disposition => "inline", :as => :view
      get 'download(/:version)', :action => :file, :disposition => "attachment", :as => :download
    end
  end

  devise_for :users
  resources :users

  get 'config' => 'sysconfigs#edit', :as => :edit_config
  post 'config' => 'sysconfigs#update', :as => :update_config
  put 'config' => 'sysconfigs#update', :as => :update_config

  match 'view/tmp/*tmp_file' => 'file#file', :as => :view_temp
  match 'view/:disposition/:class_name/:field_name/:id(/:version)'  => 'file#file', :as => :view

  root :to => "regulations#index"

end

source/app/models/expression.rb
class Expression < ActiveRecord::Base

  scope :orphans,  where(:regexable_id => nil ).order(:regexable_type, :regex)

	belongs_to :regexable, :polymorphic => true
  after_commit :reinfer

  def computed_regex
    self.as_string? ? Regexp.escape(regex) : regex
  end

  def self.type(sym)
    where(:regexable_type => sym.to_s)
  end
    
  TYPES=[ :cleaner, :paragraph_starter, :paragraph_finisher, :description_detector, :date_detector ].map{|t| [ s_t(Expression, t), t.to_s ] }
 


  def reinfer
    Regulation.where(:confirmation => false).each do |reg|
      if reg.outdated?
        reg.infer_missing_data(:force => true)
        reg.save(:validate => false)
      end
    end
  end

end

source/app/controllers/expressions_controller.rb
class ExpressionsController < ApplicationController
  load_and_authorize_resource

  def index
    @expressions=Expression.orphans
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    if @expression.save
      redirect_back_or_to expressions_path
    else
      render :action => "new" 
    end
  end

  def update
    if @expression.update_attributes(params[:expression])
      redirect_back_or_to expressions_path
    else
      render :action => "edit" 
    end
  end

  def destroy
    @expression.destroy
    redirect_back_or_to expressions_path
  end

end

source/app/views/expressions/_expression_field.erb
<li class="fields">
<table>
  <tr>
    <td>
<ol>
<%= f.input :regex %>
<%= f.input :as_string %>
</ol>
</td>
<td>

  <%= link_to_remove_fields "<span>#{s_t(Expression, :destroy, :action)}</span>".html_safe, f %>
</td>
</tr>
</table>
</li>

source/app/views/expressions/_expressions.erb
<li>
<fieldset class="inputs nested">
  <%	field_name = :expressions if field_name.nil? %>
  <legend><%= defined?(legend) && legend || s_t(Expression, :collection) %></legend>
  <ol>
    <% f.fields_for field_name do |expression| %>
      <%= render :partial => "expressions/expression_field", :locals => { :f => expression, :field_name => field_name } %>
    <% end %>
    <li><span class=button>
      <%= link_to_add_fields "<span>#{s_t(Expression, :new, :action)}</span>".html_safe, f, :field_name => field_name, :partial_model => Expression %>
    </span></li>
  </ol>
</fieldset>
</li>

source/app/views/expressions/_form.html.erb
<%= semantic_form_for(@expression) do |f| %>
  <%= f.inputs do %>
  <%= f.input :regex %>
  <%= f.input :as_string %>
  <%= f.input :regexable_type, :as => :radio, :collection => Expression::TYPES %>
  <% end %>
	<%= f.buttons %>
<% end %>

source/app/views/expressions/edit.html.erb
<h1><%= s_t Expression, :edit, :actions %></h1>
<%= render 'form' %>

source/app/views/expressions/index.html.erb
<h1><%= s_t Expression, :index, :actions %></h1>
<table class="index">
  <tr>
    <th><%= s_t(Expression) %></th>
    <th><%= s_t(Expression, :type) %></th>
    <th> </th>
  </tr>
  <% @expressions.each do |expression| %>
    <tr>
      <td><%= expression.computed_regex %></td>
      <td class="nowrap"><%= s_t(Expression, expression.regexable_type) %></td>
      <td class="nowrap"><%= rud_links(expression) %></td>
    </tr>
  <% end %>
  <tr>
    <th colspan="999"> <%= create_link(Expression) %> </th>
  </tr>
</table>

source/app/views/expressions/new.html.erb
<h1><%= s_t Expression, :new, :action %></h1>
<%= render 'form' %>

source/app/views/expressions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @expression.name %>
</p>

<p>
  <b>Issuer expression:</b>
  <%= @expression.issuer_expression_id %>
</p>


<%= link_to 'Edit', edit_expression_path(@expression) %> |
<%= link_to 'Back', expressions_path %>