source/config/routes.rb
Digesto::Application.routes.draw do

  resources :categories

  get "backups/index"

  get "backups/new"

  get "backups/destroy"

  get "backups/show"

  get "/zm" => redirect("/regulations")

  resources :words
  resources :expressions
  resources :regulation_types
  resources :types 
  resources :issuers
  resources :institutions
  resources :backups

  resources :regulations do
    post 'mass_create', :action => :mass_create, :on => :collection, :as => :mass_create
    get 'missing', :action => :missing, :on => :collection, :as => :missing
    member do
      get 'view(/:version)', :action => :file, :disposition => "inline", :as => :view
      get 'download(/:version)', :action => :file, :disposition => "attachment", :as => :download
    end
  end

  devise_for :users
  resources :users

  get 'config' => 'sysconfigs#edit', :as => :edit_config
  post 'config' => 'sysconfigs#update', :as => :update_config
  put 'config' => 'sysconfigs#update', :as => :update_config

  match 'view/tmp/*tmp_file' => 'file#file', :as => :view_temp
  match 'view/:disposition/:class_name/:field_name/:id(/:version)'  => 'file#file', :as => :view

  root :to => "regulations#index"

end

source/app/controllers/types_controller.rb
class TypesController < ApplicationController
  load_and_authorize_resource
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    if @type.save
      redirect_back_or_to types_path
    else
      render :action => "new" 
    end
  end

  def update
    if @type.update_attributes(params[:type])
      redirect_back_or_to types_path
    else
      render :action => "edit" 
    end
  end

  def destroy
    @type.destroy
    redirect_back_or_to types_path
  end

  def detectors_index
    @types=Type.scoped
  end

end

source/app/helpers/types_helper.rb
module TypesHelper
end

source/app/views/types/_form.html.erb
<%= semantic_form_for(@type) do |f| %>
	<%= f.inputs do %>
		<%= f.input :name %>
		<%= f.input :abbreviation %>
    <%= f.input :issuers, :as => :check_boxes %>
    <%= render :partial => "expressions/expressions", :locals => { :f =>  f, :legend => s_t(Type, :number_detectors) }  %>
	<% end %>
	<%= f.buttons %>
<% end %>

source/app/views/types/detectors_index.erb
<h1><%= s_t Type, :detectors %></h1>
<table>
  <tr>
    <th><%= s_t(Type, :collection) %></th>
    <th><%= s_t(Type, :regexes) %></th>
    <th> </th>
  </tr>
  <% @types.each do |type| %>
    <tr>
      <td><%= type.name %></td>
      <td>
        <% type.expressions.each do |e| %>
          <%= e.computed_regex %><br/>
        <% end %>
      </td>
      <td><%= rud_links type %></td>
    </tr>
  <% end %>
  <tr>
    <th colspan="999"> <%= create_link(RegulationType) %> </th>
  </tr>
</table>

source/app/views/types/edit.html.erb
<h1><%= s_t Type, :edit, :actions %></h1>
<%= render 'form' %>

source/app/views/types/index.html.erb
<h1><%= s_t Type, :index, :actions %></h1>
<table class="index">
  <tr>
    <th colspan="2"><%= s_t(Type, :name) %></th>
    <th><%= s_t(Type, :issuers) %></th>
    <th><%= s_t(Type, :number_detectors) %></th>
    <th> </th>
  </tr>
  <% @types.each do |type| %>
    <tr>
      <td class="right">(<%= type.abbreviation %>)</td>
      <td><%= type.name %></td>
      <td>
        <% type.issuers.each do |i| %>
          <%= i.name %> <%= i.institution.name %><br/>
        <% end %>
      </td>
      <td>
        <%= type.expressions.each.map{|e| e.computed_regex}.join("<br/><br/>").html_safe %>
      </td>
      <td class="nowrap"><%= rud_links(type) %></td>
    </tr>
  <% end %>
  <tr>
    <th colspan="999"> <%= create_link(Type) %> </th>
  </tr>
</table>

source/app/views/types/new.html.erb
<h1><%= s_t Type, :new, :action %></h1>
<%= render 'form' %>

source/app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @type.name %>
</p>

<p>
  <b>Issuer type:</b>
  <%= @type.issuer_type_id %>
</p>


<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>